<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Oleh Burdukov">
<meta name="dcterms.date" content="2026-10-03">

<title>Portfolio Optimisation Project</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="pf_management_files/libs/clipboard/clipboard.min.js"></script>
<script src="pf_management_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="pf_management_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="pf_management_files/libs/quarto-html/popper.min.js"></script>
<script src="pf_management_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="pf_management_files/libs/quarto-html/anchor.min.js"></script>
<link href="pf_management_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="pf_management_files/libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="pf_management_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="pf_management_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="pf_management_files/libs/bootstrap/bootstrap-917079515d91bccb85b543faf8aa8bb6.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#portfolio-analysis" id="toc-portfolio-analysis" class="nav-link" data-scroll-target="#portfolio-analysis"><span class="header-section-number">2</span> Portfolio analysis</a>
  <ul class="collapse">
  <li><a href="#portfolio-details" id="toc-portfolio-details" class="nav-link" data-scroll-target="#portfolio-details"><span class="header-section-number">2.1</span> Portfolio details</a></li>
  <li><a href="#initial-data-manipulations" id="toc-initial-data-manipulations" class="nav-link" data-scroll-target="#initial-data-manipulations"><span class="header-section-number">2.2</span> Initial data manipulations</a></li>
  <li><a href="#returns-plots-and-statistics" id="toc-returns-plots-and-statistics" class="nav-link" data-scroll-target="#returns-plots-and-statistics"><span class="header-section-number">2.3</span> Returns plots and statistics</a>
  <ul class="collapse">
  <li><a href="#findings" id="toc-findings" class="nav-link" data-scroll-target="#findings"><span class="header-section-number">2.3.1</span> Findings</a></li>
  </ul></li>
  <li><a href="#correlation" id="toc-correlation" class="nav-link" data-scroll-target="#correlation"><span class="header-section-number">2.4</span> Correlation</a></li>
  <li><a href="#portfolio-performance" id="toc-portfolio-performance" class="nav-link" data-scroll-target="#portfolio-performance"><span class="header-section-number">2.5</span> Portfolio performance</a></li>
  </ul></li>
  <li><a href="#optimised-portfolio-analysis" id="toc-optimised-portfolio-analysis" class="nav-link" data-scroll-target="#optimised-portfolio-analysis"><span class="header-section-number">3</span> Optimised portfolio analysis</a>
  <ul class="collapse">
  <li><a href="#returns-plots-and-statistics-1" id="toc-returns-plots-and-statistics-1" class="nav-link" data-scroll-target="#returns-plots-and-statistics-1"><span class="header-section-number">3.1</span> Returns plots and statistics</a></li>
  <li><a href="#findings-1" id="toc-findings-1" class="nav-link" data-scroll-target="#findings-1"><span class="header-section-number">3.2</span> Findings</a></li>
  <li><a href="#correlation-1" id="toc-correlation-1" class="nav-link" data-scroll-target="#correlation-1"><span class="header-section-number">3.3</span> Correlation</a></li>
  <li><a href="#portfolio-construction" id="toc-portfolio-construction" class="nav-link" data-scroll-target="#portfolio-construction"><span class="header-section-number">3.4</span> Portfolio construction</a></li>
  </ul></li>
  <li><a href="#risk-analytics" id="toc-risk-analytics" class="nav-link" data-scroll-target="#risk-analytics"><span class="header-section-number">4</span> Risk analytics</a>
  <ul class="collapse">
  <li><a href="#market-risk" id="toc-market-risk" class="nav-link" data-scroll-target="#market-risk"><span class="header-section-number">4.1</span> Market risk</a>
  <ul class="collapse">
  <li><a href="#findings-2" id="toc-findings-2" class="nav-link" data-scroll-target="#findings-2"><span class="header-section-number">4.1.1</span> Findings</a></li>
  </ul></li>
  <li><a href="#value-at-risk-analysis" id="toc-value-at-risk-analysis" class="nav-link" data-scroll-target="#value-at-risk-analysis"><span class="header-section-number">4.2</span> Value-at-Risk analysis</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">5</span> Conclusion</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="pf_management.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Portfolio Optimisation Project</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Oleh Burdukov </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 3, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>This is a project on Portfolio Optimisation. It was created to practice freshly acquired skills in Python that I had been learning in Summer 2026. The main goal was to consolidate my knowledge of Python through a basic financial engineering application. While the topic is one of the classiest assignments in quantitative finance, I aimed to push the scope by integrating as many technical skills and analytical techniques as I could.</p>
<p>The portfolio analysed in this work was provided to me by a personal contact. Taking this opportunity, I’d like to express my big gratitude to this person. Bellow, I will first introduce the portfolio and then present my work step by step shortly explaining what I did in every part of my code.</p>
</section>
<section id="portfolio-analysis" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Portfolio analysis</h1>
<section id="portfolio-details" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="portfolio-details"><span class="header-section-number">2.1</span> Portfolio details</h2>
<p>The portfolio I was given had been in possession of the owner for around the last six months. The owner was keen on investing into largely diversified ETFs that track some of the most famous market indices. In particular, she had 2 assets in her portfolio, namely Vanguard’s ETFs for S&amp;P500 and FTSE All-world indices. The weightings were 13,54% for S&amp;P500 and 86,46% for FTSE All-world. The main concern that has come up on my end after the first quick analysis involves the risk statistics of both assets, mostly regarding correlation of both assets. Due to this issue, I suggested conducting a portfolio analysis with further diversification goal.</p>
<p>It is important to note, that both acquired ETFs have been traded on the market approximately for the last 7 years. This means for us that we require some appropriate proxies for both assets, as the present time series are not long enough for a sufficient analysis. Since our investments track well-known indices, we have no problem to download 15 years of data to conduct a robust research for our purposes. Later, we’ll merely have to appreciate for some additional costs for services, when adjusting our final results. In order to verify reliability of this approach, you can check on past performance in ETFs’ documentation.</p>
<p>There is another important detail regarding such proxies. All of them are initially presented in dollars. Since portfolio owner is a UK resident, we have to appreciate for GBP/USD rate, as all presented assets in the analysis have no hedge against FX risk. Here is to note, that the FX rate dataset used for this purpose has GBP/USD indirect quote, i.e., price for one GBP in dollars.</p>
</section>
<section id="initial-data-manipulations" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="initial-data-manipulations"><span class="header-section-number">2.2</span> Initial data manipulations</h2>
<p>For a start, let’s import the data:</p>
<div id="6674f715" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>GBPUSD <span class="op">=</span> pd.read_csv(<span class="st">'Client/Proxies/GBP_USD Historical Data.csv'</span>, parse_dates <span class="op">=</span> [<span class="st">'Date'</span>], index_col <span class="op">=</span> <span class="st">'Date'</span>, thousands <span class="op">=</span> <span class="st">','</span>, na_values <span class="op">=</span> <span class="st">'n/a'</span>).sort_index(ascending <span class="op">=</span> <span class="va">True</span>) <span class="co"># import of GBP/USD indirect quote</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>sp500 <span class="op">=</span> pd.read_csv(<span class="st">'Client/Proxies/S&amp;P 500 Historical Data.csv'</span>, parse_dates <span class="op">=</span> [<span class="st">'Date'</span>], index_col <span class="op">=</span> <span class="st">'Date'</span>, thousands <span class="op">=</span> <span class="st">','</span>, na_values <span class="op">=</span> <span class="st">'n/a'</span>).sort_index(ascending <span class="op">=</span> <span class="va">True</span>) <span class="co"># import of S&amp;P500 proxy</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>ftse_allworld <span class="op">=</span> pd.read_csv(<span class="st">'Client/Proxies/FTSE All World Historical Data.csv'</span>, parse_dates <span class="op">=</span> [<span class="st">'Date'</span>], index_col <span class="op">=</span> <span class="st">'Date'</span>, na_values <span class="op">=</span> <span class="st">'n/a'</span>).sort_index(ascending <span class="op">=</span> <span class="va">True</span>) <span class="co"># import of FTSE All world proxy</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>I have shaped the data into appropriate time series for the further analysis, e.g., I’ve set the Date column as an index, sorted the whole table by it and addressed the missing values in the data frame.</p>
<p>Next, we’d like to create the return columns. Since we’ll perform modelling for required inference, it’d be better to make use of continuous returns, i.e., log transform the simple returns column once it’s computed. Additinally, we estimate also a cumulative log returns column for the plotting purposes.</p>
<div id="48f5931f" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>GBPUSD[<span class="st">'Return, daily'</span>] <span class="op">=</span> GBPUSD[<span class="st">'Price'</span>].pct_change(periods <span class="op">=</span> <span class="dv">1</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>sp500[<span class="st">'Return, daily'</span>] <span class="op">=</span> (sp500[<span class="st">'Price'</span>].pct_change(periods <span class="op">=</span> <span class="dv">1</span>).add(<span class="dv">1</span>)).div(GBPUSD[<span class="st">'Return, daily'</span>].add(<span class="dv">1</span>)).sub(<span class="dv">1</span>) <span class="co"># simple returns</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>sp500[<span class="st">'Log return, daily'</span>] <span class="op">=</span> np.log(sp500[<span class="st">'Return, daily'</span>].add(<span class="dv">1</span>)) <span class="co"># log returns</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>sp500[<span class="st">'Cumulative log return, daily'</span>] <span class="op">=</span> np.cumsum(sp500[<span class="st">'Log return, daily'</span>]) <span class="co"># cumulative log returns</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>ftse_allworld[<span class="st">'Return, daily'</span>] <span class="op">=</span> (ftse_allworld[<span class="st">'Price'</span>].pct_change(periods <span class="op">=</span> <span class="dv">1</span>).add(<span class="dv">1</span>)).div(GBPUSD[<span class="st">'Return, daily'</span>].add(<span class="dv">1</span>)).sub(<span class="dv">1</span>) <span class="co"># simple returns</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>ftse_allworld[<span class="st">'Log return, daily'</span>] <span class="op">=</span> np.log(ftse_allworld[<span class="st">'Return, daily'</span>].add(<span class="dv">1</span>)) <span class="co"># log returns</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>ftse_allworld[<span class="st">'Cumulative log return, daily'</span>] <span class="op">=</span> np.cumsum(ftse_allworld[<span class="st">'Log return, daily'</span>]) <span class="co"># cumulative log returns</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>At this point it was noticed that FTSE All world index starts a bit later than 15 years ago. We assume it doesn’t corrupt analysis and allign length of both time series</p>
<div id="9a0ae060" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>sp500 <span class="op">=</span> sp500.loc[<span class="st">'10/14/2013'</span>:<span class="st">'09/15/2026'</span>] <span class="co"># cutting the data</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="returns-plots-and-statistics" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="returns-plots-and-statistics"><span class="header-section-number">2.3</span> Returns plots and statistics</h2>
<p>Now, as we have successfully maintained the data, we are good to construct some plots and observe statistic tables for the assets analysis.</p>
<div id="f94f0d11" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>LogReturnsData <span class="op">=</span> pd.DataFrame({<span class="st">'sp500'</span> : sp500[<span class="st">'Log return, daily'</span>],</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>                               <span class="st">'sp500, cumulative'</span> : sp500[<span class="st">'Cumulative log return, daily'</span>],</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>                               <span class="st">'ftse_allworld'</span> : ftse_allworld[<span class="st">'Log return, daily'</span>],</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>                               <span class="st">'ftse_allworld, cumulative'</span> : ftse_allworld[<span class="st">'Cumulative log return, daily'</span>]}) <span class="co"># Assignment of the log returns dataframe for further modelling manipulations</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We are going to plot returns by 2 graphs, one for log returns themselves and one for the cumulative representiation.</p>
<div id="7cc1fc5d" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>LogReturnsData[[<span class="st">'sp500'</span>, <span class="st">'ftse_allworld'</span>]].plot(subplots <span class="op">=</span> <span class="va">True</span>) <span class="co"># plot of simple log returns</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>LogReturnsData[[<span class="st">'sp500, cumulative'</span>, <span class="st">'ftse_allworld, cumulative'</span>]].plot(kind <span class="op">=</span> <span class="st">'line'</span>) <span class="co"># plot of cumulative log returns</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="pf_management_files/figure-html/cell-7-output-1.png" width="590" height="401" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="pf_management_files/figure-html/cell-7-output-2.png" width="571" height="401" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>As we may read it from the plots above, the correlation between both ETFs is drammaticaly strong. Such investment allocation may be as successful as investment in only one of both assets. Obviously, we are going to see similar picture on the following statistic tables.</p>
<p>In order to obtain all necessary values for sufficient analysis, we’ll assign first table by means of the .describe() method and second using .agg() . Additionally, we’ll annualise mean return and standard deviation.</p>
<div id="b9d73f91" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>statistics1 <span class="op">=</span> LogReturnsData[[<span class="st">'sp500'</span>, <span class="st">'ftse_allworld'</span>]].describe() <span class="co"># descriptive statistics</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(statistics1)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>statistics2 <span class="op">=</span> LogReturnsData[[<span class="st">'sp500'</span>, <span class="st">'ftse_allworld'</span>]].agg([<span class="st">'median'</span>, <span class="st">'var'</span>, <span class="st">'skew'</span>, <span class="st">'kurtosis'</span>]) <span class="co"># descriptive statistics</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(statistics2)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>annual_mean <span class="op">=</span> np.exp(statistics1.loc[<span class="st">'mean'</span>].mul(<span class="dv">252</span>)).sub(<span class="dv">1</span>) <span class="co"># reverse the log transformation and annualise return</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'annual mean values are:</span><span class="ch">\n</span><span class="st">'</span>, annual_mean)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>annual_std <span class="op">=</span> statistics1.loc[<span class="st">'std'</span>].mul(np.sqrt(<span class="dv">252</span>)) <span class="co"># annualise standard deviation value</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'annual standard deviation values are:</span><span class="ch">\n</span><span class="st">'</span>, annual_std)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             sp500  ftse_allworld
count  3249.000000    3378.000000
mean      0.000517       0.000375
std       0.010977       0.008516
min      -0.126842      -0.093779
25%      -0.004600      -0.003628
50%       0.000884       0.000612
75%       0.006153       0.004814
max       0.112564       0.073736
              sp500  ftse_allworld
median     0.000884       0.000612
var        0.000121       0.000073
skew      -0.308484      -0.723854
kurtosis  15.768773      14.134924
annual mean values are:
 sp500            0.139041
ftse_allworld    0.099238
Name: mean, dtype: float64
annual standard deviation values are:
 sp500            0.174259
ftse_allworld    0.135194
Name: std, dtype: float64</code></pre>
</div>
</div>
<p>Portfolio owner asked me to optimise it, such that a better of two assets stays on the books. At this point, we need to choose one of the assets based on descriptive statistics, in order to substitute a worse investment with an alternative.</p>
<section id="findings" class="level3" data-number="2.3.1">
<h3 data-number="2.3.1" class="anchored" data-anchor-id="findings"><span class="header-section-number">2.3.1</span> Findings</h3>
<p>Fisrt finding that we can see is negative skewness of both indices. These values basically say that while retruns are mostly placed around mean and are positive, considerable share of outliers in the data is negative, i.e., ususally market shocks lead to some big falls in value, not to its rises. Preferably, we want to have assets with positive skewness, but in these terms, S&amp;P500 is what we may keep working with later.</p>
<p>Furthermore, kurtosis value of each ETF appears to be very large. Ideally, we’d have a value arround 3, but the present distributions’ kurtosis says it is pretty much leptokurtic, which means tails are longer and thicker, and central peak is higher and sharper. In fact, this is more than possible, considering the issuer of both tracking ETFs states level of risk 6 out of 7 in the documentation. Later, you’ll be able to observe this issue on the distribution plot.</p>
<p>Taken together, the picture we observe in both tables allows us to state the following: the kurtosis coefficients correspond to what one can observe in the minimum and maximum values of both series. The outliers of S&amp;P500 extend further from the mean, than those of FTSE All-world. It also relates to what we can read from lower and upper quartile of distributions. Perhaps, more negative skewness of FTSE All-world indicates a higher share of losses among the outliers, whereas the skewness of S&amp;P500 does not raise such concerns and appears more promising in light of the above facts.</p>
<p>Last but not least, what one can make some conclusions from is mean and standard deviation of both assets. Comparing both ETFs, we notice that S&amp;P500 has relatively high volatility of 17%, even if the mean return is greater than that of FTSE all-world.</p>
<p>Now, we can summarise the observation by distribution plot</p>
<div id="6bb18d09" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>plt.hist(x <span class="op">=</span> LogReturnsData[[<span class="st">'sp500'</span>, <span class="st">'ftse_allworld'</span>]], </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>         bins <span class="op">=</span> <span class="dv">50</span>, </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>         density <span class="op">=</span> <span class="va">True</span>, </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>         alpha <span class="op">=</span> <span class="fl">0.5</span>, </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>         label <span class="op">=</span> [<span class="st">'Distribution of Vanguard S&amp;P500'</span>, <span class="st">'Distribution of Vanguard FTSE All world'</span>]) <span class="co"># histogram of distribution for both assets</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Daily log returns'</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Density'</span>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Distribution of both ETFs'</span>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="pf_management_files/figure-html/cell-9-output-1.png" width="585" height="449" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Taking into account all findings and the latter plot, we can come to conclusion that it’d be a rather better idea to exclude FTSE all world, if we have to keep one of investments, as the owner requested.</p>
</section>
</section>
<section id="correlation" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="correlation"><span class="header-section-number">2.4</span> Correlation</h2>
<p>As I spoiled it at the very beginning (and as one might have seen on the cumulative returns graph), correlation issue in the portfolio is drammatic and must be addressed as part of optimisation.</p>
<p>The following heatmap visualises the correlations.</p>
<div id="473f404e" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>correlation <span class="op">=</span> LogReturnsData[[<span class="st">'sp500'</span>, <span class="st">'ftse_allworld'</span>]].corr() <span class="co"># privides with correlation value</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>sbn.heatmap(correlation,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>            annot <span class="op">=</span> <span class="va">True</span>,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>            cmap <span class="op">=</span> <span class="st">'YlGnBu'</span>,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>            vmin <span class="op">=</span> <span class="op">-</span><span class="dv">1</span>, vmax <span class="op">=</span> <span class="dv">1</span>) <span class="co"># heatmap for correlation visualisation</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="pf_management_files/figure-html/cell-10-output-1.png" width="553" height="416" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>So, as we may conclude, the diagnosis in our case is obvious: both investments essentially follow each other’s movement, which certainly must be fixed.</p>
</section>
<section id="portfolio-performance" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="portfolio-performance"><span class="header-section-number">2.5</span> Portfolio performance</h2>
<p>For comparison purposes, let’s now check portfolio performance given the initial assets and weights.</p>
<p>As the owner is located in the UK, we are going to use risk-free interest rate offered by Bank of England as of this project’s publishment date. At this moment, BoE’s rate is 3.75% p.a.</p>
<p>According to portfolio holder, 86.46% of capital is allocated in the FTSE all world ETF and 13.54% in S&amp;P500 ETF.</p>
<p>Mind that our investor is not risk averse, from what we conclude it’d be more optimal to consider tangency portfolio later, rather than global minimum volatility option.</p>
<div id="14263f61" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>risk_free <span class="op">=</span> <span class="fl">0.0375</span> <span class="co"># assignment of risk-free rate</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>PriceData <span class="op">=</span> pd.DataFrame({<span class="st">'sp500'</span> : sp500[<span class="st">'Price'</span>].div(GBPUSD[<span class="st">'Price'</span>]),</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>                          <span class="st">'ftse_allworld'</span> : ftse_allworld[<span class="st">'Price'</span>].div(GBPUSD[<span class="st">'Price'</span>])}) <span class="co"># Price dataframe</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>mu <span class="op">=</span> expected_returns.mean_historical_return(PriceData) <span class="co"># computation of assets' annual mean</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>Sigma <span class="op">=</span> risk_models.sample_cov(PriceData) <span class="co"># computation of annual assets' volatility </span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>EF_undiv <span class="op">=</span> EfficientFrontier(mu, Sigma) <span class="co"># Efficient frontier</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>EF_undiv.set_weights({<span class="st">'sp500'</span> : <span class="fl">0.1354</span>,</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>                      <span class="st">'ftse_allworld'</span> : <span class="fl">0.8646</span>}) <span class="co"># manual weights assignment</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>EF_undiv.portfolio_performance(verbose <span class="op">=</span> <span class="va">True</span>, risk_free_rate <span class="op">=</span> risk_free) <span class="co"># annual mean and volatility of portfolio</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>cleaned_weights <span class="op">=</span> EF_undiv.clean_weights()</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(cleaned_weights) <span class="co"># output of pre-assigned weights to present full information.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Expected annual return: 10.6%
Annual volatility: 14.0%
Sharpe Ratio: 0.49
OrderedDict([('sp500', 0.1354), ('ftse_allworld', 0.8646)])</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/Users/olegburdukov/Library/Python/3.9/lib/python/site-packages/pypfopt/expected_returns.py:32: UserWarning: Some returns are NaN. Please check your price data.
  warnings.warn(</code></pre>
</div>
</div>
<p>In the code output we can observe quite low annual return of portfolio, especially if we look at volatility measure. 14% of volatility for 10.6% of return is unnecessary risk, to put it mildly. Another value which would easily raise concerns is the sharpe ratio of 0.49. It is definitelly low and the new asset should address this inefficiency, too.</p>
</section>
</section>
<section id="optimised-portfolio-analysis" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Optimised portfolio analysis</h1>
<p>We now observe the substitute asset, which is gold ETC. This exchange traded commodity was issued by Wisdom Tree and in order to efficiently observe it, we’ll take the Gold USD spot for the period of 15 last years as a proxy and appreciate for FX rate.</p>
<p>The procedure with the data maintenance is more or less the same as before.</p>
<div id="532c2c97" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>sp500 <span class="op">=</span> pd.read_csv(<span class="st">'Client/Proxies/S&amp;P 500 Historical Data.csv'</span>, parse_dates <span class="op">=</span> [<span class="st">'Date'</span>], index_col <span class="op">=</span> <span class="st">'Date'</span>, thousands <span class="op">=</span> <span class="st">','</span>, na_values <span class="op">=</span> <span class="st">'n/a'</span>).sort_index(ascending <span class="op">=</span> <span class="va">True</span>) <span class="co"># reimport of this dataset due to it being cut during previous analysis part</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>gold <span class="op">=</span> pd.read_csv(<span class="st">'Client/Proxies/XAU_USD Historical Data.csv'</span>, parse_dates <span class="op">=</span> [<span class="st">'Date'</span>], index_col <span class="op">=</span> <span class="st">'Date'</span>, thousands <span class="op">=</span> <span class="st">','</span>, na_values <span class="op">=</span> <span class="st">'n/a'</span>).sort_index(ascending <span class="op">=</span> <span class="va">True</span>) <span class="co"># data for gold ETC proxy</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>sp500[<span class="st">'Return, daily'</span>] <span class="op">=</span> (sp500[<span class="st">'Price'</span>].pct_change(periods <span class="op">=</span> <span class="dv">1</span>).add(<span class="dv">1</span>)).div(GBPUSD[<span class="st">'Return, daily'</span>].add(<span class="dv">1</span>)).sub(<span class="dv">1</span>) <span class="co"># simple returns</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>sp500[<span class="st">'Log return, daily'</span>] <span class="op">=</span> np.log(sp500[<span class="st">'Return, daily'</span>].add(<span class="dv">1</span>)) <span class="co"># log returns</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>sp500[<span class="st">'Cumulative log return, daily'</span>] <span class="op">=</span> np.cumsum(sp500[<span class="st">'Log return, daily'</span>]) <span class="co"># cumulative log returns</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>gold[<span class="st">'Return, daily'</span>] <span class="op">=</span> (gold[<span class="st">'Price'</span>].pct_change(periods <span class="op">=</span> <span class="dv">1</span>).add(<span class="dv">1</span>)).div(GBPUSD[<span class="st">'Return, daily'</span>].add(<span class="dv">1</span>)).sub(<span class="dv">1</span>) <span class="co"># simple returns</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>gold[<span class="st">'Log return, daily'</span>] <span class="op">=</span> np.log(gold[<span class="st">'Return, daily'</span>].add(<span class="dv">1</span>)) <span class="co"># log returns</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>gold[<span class="st">'Cumulative log return, daily'</span>] <span class="op">=</span> np.cumsum(gold[<span class="st">'Log return, daily'</span>]) <span class="co"># cumulative log returns</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="returns-plots-and-statistics-1" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="returns-plots-and-statistics-1"><span class="header-section-number">3.1</span> Returns plots and statistics</h2>
<p>As before, we first plot returns and analyse descriptive statistics</p>
<div id="eeb56eac" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>LogReturnsData <span class="op">=</span> pd.DataFrame({<span class="st">'sp500'</span> : sp500[<span class="st">'Log return, daily'</span>],</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>                               <span class="st">'sp500, cumulative'</span> : sp500[<span class="st">'Cumulative log return, daily'</span>],</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>                               <span class="st">'gold'</span> : gold[<span class="st">'Log return, daily'</span>],</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>                               <span class="st">'gold, cumulative'</span> : gold[<span class="st">'Cumulative log return, daily'</span>]}) <span class="co"># Assignment of the log returns dataframe for further modelling manipulations</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>LogReturnsData[[<span class="st">'sp500'</span>, <span class="st">'gold'</span>]].plot(subplots <span class="op">=</span> <span class="va">True</span>) <span class="co"># simple log returns</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>LogReturnsData[[<span class="st">'sp500, cumulative'</span>, <span class="st">'gold, cumulative'</span>]].plot(kind <span class="op">=</span> <span class="st">'line'</span>) <span class="co"># cumulative log returns</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>statistics1 <span class="op">=</span> LogReturnsData[[<span class="st">'sp500'</span>, <span class="st">'gold'</span>]].describe() <span class="co"># descriptive statistics</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(statistics1)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>statistics2 <span class="op">=</span> LogReturnsData[[<span class="st">'sp500'</span>, <span class="st">'gold'</span>]].agg([<span class="st">'median'</span>, <span class="st">'var'</span>, <span class="st">'skew'</span>, <span class="st">'kurtosis'</span>]) <span class="co"># descriptive statistics</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(statistics2)</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>annual_mean <span class="op">=</span> np.exp(statistics1.loc[<span class="st">'mean'</span>].mul(<span class="dv">252</span>)).sub(<span class="dv">1</span>) <span class="co"># reverse the log transformation and annualise return</span></span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'annualised mean return values are:</span><span class="ch">\n</span><span class="st">'</span>, annual_mean)</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>annual_std <span class="op">=</span> statistics1.loc[<span class="st">'std'</span>].mul(np.sqrt(<span class="dv">252</span>)) <span class="co"># annualise standard deviation value</span></span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'annualised standard deviation values of returns are:</span><span class="ch">\n</span><span class="st">'</span>, annual_std)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="pf_management_files/figure-html/cell-13-output-1.png" width="590" height="401" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="pf_management_files/figure-html/cell-13-output-2.png" width="582" height="401" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>             sp500         gold
count  3769.000000  3903.000000
mean      0.000550     0.000284
std       0.010689     0.010093
min      -0.126842    -0.094842
25%      -0.004540    -0.004778
50%       0.000775     0.000278
75%       0.006073     0.005530
max       0.112564     0.131023
              sp500       gold
median     0.000775   0.000278
var        0.000114   0.000102
skew      -0.286494  -0.045204
kurtosis  15.233218  12.906596
annualised mean return values are:
 sp500    0.148584
gold     0.074073
Name: mean, dtype: float64
annualised standard deviation values of returns are:
 sp500    0.169690
gold     0.160227
Name: std, dtype: float64</code></pre>
</div>
</div>
</section>
<section id="findings-1" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="findings-1"><span class="header-section-number">3.2</span> Findings</h2>
<p>Now, the output is much more promising. Of course we first see it on the graphs. Returns do not appear to share the same path across the whole time series any longer . Regarding the descriptive statistics, they also suggest a better picture, although not perfect. For example, despite the skewness of gold is still negative, its value is now close to 0, which is good. It essentially indicates that outliers are almost equally distributed in the both tails, which means better chances for the positive shocks. The value for kurtosis has also been reduced. It might be still far from what we wish to see, i.e., around 3, but 12.9 is what we at least can work with more securely.</p>
<p>What might raise some concens about gold, is lower return for a slightly higher standard deviation, comparing to all-world index. Perhaps, it is still not a big problem, considering other metrics with better values and the ultimate results in the end.</p>
<p>Summarising, we can again have a look at the new distribution plot.</p>
<div id="47f2e2f2" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>plt.hist(x <span class="op">=</span> LogReturnsData[[<span class="st">'sp500'</span>, <span class="st">'gold'</span>]],</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>         bins <span class="op">=</span> <span class="dv">50</span>,</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>         density <span class="op">=</span> <span class="va">True</span>,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>         alpha <span class="op">=</span> <span class="fl">0.5</span>,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>         label <span class="op">=</span> [<span class="st">'Distribution of S&amp;P500'</span>, <span class="st">'Distribution of XAU/GBP Gold Spot'</span>])</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Daily log returns'</span>)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Density'</span>)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Distribution of both assets'</span>)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="pf_management_files/figure-html/cell-14-output-1.png" width="585" height="449" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="correlation-1" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="correlation-1"><span class="header-section-number">3.3</span> Correlation</h2>
<div id="87b93aa4" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>correlation <span class="op">=</span> LogReturnsData[[<span class="st">'sp500'</span>, <span class="st">'gold'</span>]].corr()</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>sbn.heatmap(correlation,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>            annot <span class="op">=</span> <span class="va">True</span>,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>            cmap <span class="op">=</span> <span class="st">'YlGnBu'</span>,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>            vmin <span class="op">=</span> <span class="op">-</span><span class="dv">1</span>, vmax <span class="op">=</span> <span class="dv">1</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="pf_management_files/figure-html/cell-15-output-1.png" width="553" height="416" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>As cumulative returns graph allowed to suspect, correlation between these assets is just what we were looking for.</p>
<p>After the analysis, we can confidently say that the asset, albeit flawed, can deliver on our goal during the new portfolio construction.</p>
</section>
<section id="portfolio-construction" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="portfolio-construction"><span class="header-section-number">3.4</span> Portfolio construction</h2>
<div id="c948a291" class="cell" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>PriceData <span class="op">=</span> pd.DataFrame({<span class="st">'sp500'</span> : sp500[<span class="st">'Price'</span>].div(GBPUSD[<span class="st">'Price'</span>]),</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>                          <span class="st">'gold'</span> : gold[<span class="st">'Price'</span>].div(GBPUSD[<span class="st">'Price'</span>])})</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>mu <span class="op">=</span> expected_returns.mean_historical_return(PriceData)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>Sigma <span class="op">=</span> risk_models.sample_cov(PriceData)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>EF_div <span class="op">=</span> EfficientFrontier(mu, Sigma)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>EF_div.max_sharpe(risk_free) <span class="co"># weights are no longer assigned manually, as we are looking for the best return-volatility combination, i.e., we should obtain the tangency portfolio</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>EF_div.portfolio_performance(verbose <span class="op">=</span> <span class="va">True</span>, risk_free_rate <span class="op">=</span> risk_free)</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>cleaned_weights <span class="op">=</span> EF_div.clean_weights()</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(cleaned_weights)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Expected annual return: 13.2%
Annual volatility: 14.3%
Sharpe Ratio: 0.66
OrderedDict([('sp500', 0.81152), ('gold', 0.18848)])</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/Users/olegburdukov/Library/Python/3.9/lib/python/site-packages/pypfopt/expected_returns.py:32: UserWarning: Some returns are NaN. Please check your price data.
  warnings.warn(</code></pre>
</div>
</div>
<p>From the output, we can draw 2 conclusions:</p>
<ul>
<li><p>For a 0.3% increase of volatility we have reached 2.6% additional return with the alternative asset. Volatility 14.3% itself can be perceived as tolerable in our case, as the holder has a higher risk tolerance and is ready to take additional risk for a higher profit, if necessary.</p></li>
<li><p>An increased Sharpe Ratio serves as additional proof for a successfully optimised portfolio.</p></li>
</ul>
<p>In other words, our portfolio optimisation has led to positive results in terms of risk-return ratio and the initial goal has been successfully achieved.</p>
<p>In the following analysis, we are going to study the risk metrics of the freshly shaped product to get a broader perspective on its quality and sustainability</p>
</section>
</section>
<section id="risk-analytics" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Risk analytics</h1>
<section id="market-risk" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="market-risk"><span class="header-section-number">4.1</span> Market risk</h2>
<p>Let’s consider one of the most classic market risk metrics, the CAPM’s beta factor. I decided to estimate it by means of linar regression in this work, although one can easily perform it in the other way.</p>
<p>Estimation assumes excessive return for both market and studied portfolio as an input. So, we have yet to appreciate both log returns time series for the daily risk-free rate. Mind that log returns are not to add or subtract between the assets, as its exponentialised result won’t be correct. From it follows that one has to exponentialise log retruns, subtract the daily risk-free, and then log transform the new series to proceed with modelling. Perhaps, we might say that the estimation error of log transformed difference of simple returns is low enough to difference of logarithmised returns and stick to the latter, easier approach.</p>
<div id="6eb9db56" class="cell" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>LogReturnsData[<span class="st">'Benchmark log return, daily'</span>] <span class="op">=</span> LogReturnsData[<span class="st">'sp500'</span>]</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>LogReturnsData[<span class="st">'Excess Benchmark log return, daily'</span>] <span class="op">=</span> LogReturnsData[<span class="st">'Benchmark log return, daily'</span>].sub(np.log(<span class="dv">1</span> <span class="op">+</span> risk_free)<span class="op">/</span><span class="dv">252</span>) <span class="co"># Excess log returns of the benchmark</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>LogReturnsData[<span class="st">'Portfolio log return, daily'</span>] <span class="op">=</span> np.log(sp500[<span class="st">'Return, daily'</span>].mul(cleaned_weights[<span class="st">'sp500'</span>]).add(gold[<span class="st">'Return, daily'</span>].mul(cleaned_weights[<span class="st">'gold'</span>])).add(<span class="dv">1</span>))</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>LogReturnsData[<span class="st">'Excess Portfolio log return, daily'</span>] <span class="op">=</span> LogReturnsData[<span class="st">'Portfolio log return, daily'</span>].sub(np.log(<span class="dv">1</span> <span class="op">+</span> risk_free)<span class="op">/</span><span class="dv">252</span>) <span class="co"># Excess log returns of the portfolio</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Additionally, mind that our benchmark is basically also a proxy for one of the portfolio assets. In this regard, there are 2 important points:</p>
<ul>
<li><p>S&amp;P500 ETF took place in both portfolios in this work</p></li>
<li><p>Before diversification, the whole portfolio had correlation of almost 1 between its assets. Because of it, the whole initial portfolio should have the beta value of ca. 1 to the same benchmark. Diversification would then prove beneficial in terms of beta factor, if beta fell bellow this level, i.e., its exposure to the market risk would be smaller.</p></li>
</ul>
<div id="bb954ca1" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> smf.ols(formula <span class="op">=</span> <span class="st">'Q("Excess Portfolio log return, daily") ~ Q("Excess Benchmark log return, daily")'</span>, data <span class="op">=</span> LogReturnsData) <span class="co"># model data assignment</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>fit <span class="op">=</span> model.fit() <span class="co"># model construction</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(fit.summary()) <span class="co"># summary on the linear regression</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>pf_beta <span class="op">=</span> fit.params[<span class="st">'Q("Excess Benchmark log return, daily")'</span>] <span class="co"># portfolio beta factor</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pf_beta)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                       OLS Regression Results                                      
===================================================================================================
Dep. Variable:     Q("Excess Portfolio log return, daily")   R-squared:                       0.955
Model:                                                 OLS   Adj. R-squared:                  0.955
Method:                                      Least Squares   F-statistic:                 7.911e+04
Date:                                     Sat, 03 Oct 2026   Prob (F-statistic):               0.00
Time:                                             14:30:39   Log-Likelihood:                 18223.
No. Observations:                                     3769   AIC:                        -3.644e+04
Df Residuals:                                         3767   BIC:                        -3.643e+04
Df Model:                                                1                                         
Covariance Type:                                 nonrobust                                         
===========================================================================================================
                                              coef    std err          t      P&gt;|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------------
Intercept                                3.263e-05   3.14e-05      1.041      0.298   -2.88e-05    9.41e-05
Q("Excess Benchmark log return, daily")     0.8245      0.003    281.257      0.000       0.819       0.830
==============================================================================
Omnibus:                      744.355   Durbin-Watson:                   2.007
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            23196.579
Skew:                           0.077   Prob(JB):                         0.00
Kurtosis:                      15.153   Cond. No.                         93.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
0.8244832300213749</code></pre>
</div>
</div>
<p>Here, we can finish consideration of the market risk exposure by visualisation of the model</p>
<div id="0a007964" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>sbn.regplot(data <span class="op">=</span> LogReturnsData,</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>            x <span class="op">=</span> <span class="st">'Excess Benchmark log return, daily'</span>,</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>            y <span class="op">=</span> <span class="st">'Excess Portfolio log return, daily'</span>,</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>            line_kws <span class="op">=</span> {<span class="st">'color'</span> : <span class="st">'red'</span>},</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>            scatter_kws <span class="op">=</span> {<span class="st">'alpha'</span> : <span class="fl">0.6</span>})</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="pf_management_files/figure-html/cell-19-output-1.png" width="617" height="429" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<section id="findings-2" class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="findings-2"><span class="header-section-number">4.1.1</span> Findings</h3>
<p>The present linear regression model output has 2 most valuable numbers for us:</p>
<ul>
<li><p>First, it is a decreased beta factor of 0.8245. This is a good result, considering the fact our benchmark is actually the proxy analysed on one of our assets stead. In other words, diversification strategy has proven beneficial, as our beta has dropped to this value from value 1</p></li>
<li><p>Second, it is remarkably high adjusted R-squared estimate. As you might know, this value serves as a quality measure for the model. Hence, we may be confident about this model’s result and rely on its estimate for beta.</p></li>
</ul>
</section>
</section>
<section id="value-at-risk-analysis" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="value-at-risk-analysis"><span class="header-section-number">4.2</span> Value-at-Risk analysis</h2>
<p>Last, but not least, let’s define VaR and CVaR metrics for our portfolio. This part will essentially describe portfolio’s exposure to the market shocks by means of the tail risk. Value at Risk displays the least value the portfolio owner may lose with probability of ‘1 - percentile’%. In its turn, the Conditional Value at Risk, a.k.a., Expected Shortfall, measures expected loss given the same probability.</p>
<p>I decided to perform Monte Carlo simulation of a quite large scale using normal distribution. Instead of real world returns, there are going to be 5000 sets of 1-year returns time series simulation.</p>
<div id="86e018e0" class="cell" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>weights <span class="op">=</span> np.array(<span class="bu">list</span>(cleaned_weights.values())) <span class="co"># turning the weights of the tangency portfolio into an array</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>pf_mean <span class="op">=</span> np.dot(weights.T, mu) <span class="co"># annual mean return of the portfolio</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>pf_std <span class="op">=</span> np.sqrt(np.dot(weights.T, np.dot(Sigma, weights))) <span class="co"># annual standard deviation of the portfolio</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>T <span class="op">=</span> <span class="dv">252</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>simulated_returns <span class="op">=</span> []</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">5000</span>):</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>    random_returns <span class="op">=</span> np.random.normal(pf_mean, pf_std, T)</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>    simulated_returns.append(random_returns) <span class="co"># modelling of the portfolio retuns time series for one year with 5000 iterations.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>As we have the Monte Carlo simulation above, we can estimate Value at Risk and Expected Shortfall values.</p>
<div id="9c4c92c6" class="cell" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>simulated_returns <span class="op">=</span> np.array(simulated_returns).T </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>VaR_90 <span class="op">=</span> np.percentile(simulated_returns, <span class="dv">100</span> <span class="op">-</span> <span class="dv">90</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>VaR_95 <span class="op">=</span> np.percentile(simulated_returns, <span class="dv">100</span> <span class="op">-</span> <span class="dv">95</span>)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>VaR_99 <span class="op">=</span> np.percentile(simulated_returns, <span class="dv">100</span> <span class="op">-</span> <span class="dv">99</span>)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>CVaR_90 <span class="op">=</span> simulated_returns[simulated_returns <span class="op">&lt;</span> VaR_90].mean()</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>CVaR_95 <span class="op">=</span> simulated_returns[simulated_returns <span class="op">&lt;</span> VaR_95].mean()</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>CVaR_99 <span class="op">=</span> simulated_returns[simulated_returns <span class="op">&lt;</span> VaR_99].mean()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>It’s rather very useful to visualise the whole simulation to be able to comment analysis.</p>
<div id="8f9c778b" class="cell" data-execution_count="21">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>np.exp(LogReturnsData[<span class="st">'Portfolio log return, daily'</span>]).sub(<span class="dv">1</span>).plot(kind <span class="op">=</span> <span class="st">'density'</span>,</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>                                                                  rot <span class="op">=</span> <span class="dv">45</span>,</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>                                                                  title <span class="op">=</span> <span class="st">'VaR-CVaR metrics of the portfolio'</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>plt.axvline(x <span class="op">=</span> VaR_90, color <span class="op">=</span> <span class="st">'yellow'</span>, linestyle <span class="op">=</span> <span class="st">'-'</span>, label <span class="op">=</span> <span class="st">'VaR 90%'</span>)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>plt.axvline(x <span class="op">=</span> VaR_95, color <span class="op">=</span> <span class="st">'pink'</span>, linestyle <span class="op">=</span> <span class="st">'-'</span>, label <span class="op">=</span> <span class="st">'VaR 95%'</span>)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>plt.axvline(x <span class="op">=</span> VaR_99, color <span class="op">=</span> <span class="st">'red'</span>, linestyle <span class="op">=</span> <span class="st">'-'</span>, label <span class="op">=</span> <span class="st">'VaR 99%'</span>)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>plt.axvline(x <span class="op">=</span> CVaR_90, color <span class="op">=</span> <span class="st">'yellow'</span>, linestyle <span class="op">=</span> <span class="st">'--'</span>, label <span class="op">=</span> <span class="st">'CVaR 90%'</span>)</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>plt.axvline(x <span class="op">=</span> CVaR_95, color <span class="op">=</span> <span class="st">'pink'</span>, linestyle <span class="op">=</span> <span class="st">'--'</span>, label <span class="op">=</span> <span class="st">'CVaR 95%'</span>)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>plt.axvline(x <span class="op">=</span> CVaR_99, color <span class="op">=</span> <span class="st">'red'</span>, linestyle <span class="op">=</span> <span class="st">'--'</span>, label <span class="op">=</span> <span class="st">'CVaR 99%'</span>)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Daily portfolio returns'</span>)</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Density'</span>)</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'VaR-CVaR metrics of the portfolio'</span>)</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="pf_management_files/figure-html/cell-22-output-1.png" width="585" height="469" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>As one might have expected, every pair of values for each percentile presents a rather serious value loss. Perhaps, it is also the probability of such a loss what we must account for. For example, 99% CVaR represents the loss, that the portfolio owner should expect with probability of merely 1%. In other words, it’s barely possible to experience such a large shortfall over 20% with this portfolio, though not excluded.</p>
<p>The risk model itself should be seen as robust and reliable, since it incorporates 5000 different portfolio time series scenarios.</p>
</section>
</section>
<section id="conclusion" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Conclusion</h1>
<p>We have found that the optimised portfolio has annual mean return of 13.2% with 14.3% volatility. Now, we need to finish the analysis with appreciation to the ongoing charges issuers request for their services.</p>
<div id="9a105a9c" class="cell" data-execution_count="22">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>sp500charges <span class="op">=</span> <span class="fl">0.0007</span> <span class="co"># ongoing charges from Vanguard</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>goldcharges <span class="op">=</span> <span class="fl">0.0012</span> <span class="co"># Wisdom tree's management fees etc.</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>pf_return <span class="op">=</span> EF_div.portfolio_performance(risk_free_rate <span class="op">=</span> risk_free)[<span class="dv">0</span>] <span class="co"># annual mean return of the portfolio</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>adjusted_return <span class="op">=</span> pf_return <span class="op">-</span> (sp500charges<span class="op">*</span>cleaned_weights[<span class="st">'sp500'</span>] <span class="op">+</span> goldcharges<span class="op">*</span>cleaned_weights[<span class="st">'gold'</span>])</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'The total annual return after all charges is'</span>, <span class="bu">round</span>(adjusted_return<span class="op">*</span><span class="dv">100</span>, <span class="dv">4</span>), <span class="st">'%'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>The total annual return after all charges is 13.0999 %</code></pre>
</div>
</div>
<p>Summarising the whole work, I ’d like to highlight two key points. First, we have increased the expected return of the observed portfolio. Its previous state was sub-optimal, primarily due to its arbitrary weightings. Optimisation by means of efficient frontier is what actually was one of the bulletpoints in the to-do list of mine. No matter where the former portfolio could be placed on the efficient frontier graph, we still might find a better weighting, as the previous weights weren’t chosen based on any quantitative analysis. Second, the deliberate choice of the substitute asset on the non-equity market allowed to achieve the main goal of this project, namely to achieve diversification through an uncorrelated investment.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>